### ISSUE TITLE
Segfault when slicing

### ISSUE THREAD

**Issue by gyscos** [supermerill/Slic3r#4417]
### What happened?

When slicing a specific model, superslicer suddenly crashes.

Running in gdb, I get this backtrace:

```
Thread 35 "slic3r_tbb_23" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbce006c0 (LWP 558844)]
0x00005555563ae49f in Slic3r::SeamPlacerImpl::calculate_polyline_angles_at_vertices(Slic3r::SeamPlacerImpl::PolylineWithEnd const&, std::vector<float, std::allocator<float> > const&, float) ()
(gdb) bt
#0  0x00005555563ae49f in Slic3r::SeamPlacerImpl::calculate_polyline_angles_at_vertices(Slic3r::SeamPlacerImpl::PolylineWithEnd const&, std::vector<float, std::allocator<float> > const&, float) ()
#1  0x00005555563b2183 in Slic3r::SeamPlacerImpl::process_perimeter_polylines(Slic3r::SeamPlacerImpl::PolylineWithEnd const&, float, Slic3r::LayerRegion const*, Slic3r::SeamPlacerImpl::GlobalModelInfo const&, Slic3r::PrintObjectSeamData::LayerSeams&) ()
#2  0x00005555563b8285 in Slic3r::SeamPlacer::gather_seam_candidates(Slic3r::PrintObject const*, Slic3r::SeamPlacerImpl::GlobalModelInfo const&, Slic3r::SeamPosition)::{lambda(tbb::detail::d1::blocked_range<unsigned long>)#1}::operator()(tbb::detail::d1::blocked_range<unsigned long>) const [clone .isra.0] ()
#3  0x00005555563b8a44 in tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, Slic3r::SeamPlacer::gather_seam_candidates(Slic3r::PrintObject const*, Slic3r::SeamPlacerImpl::GlobalModelInfo const&, Slic3r::SeamPosition)::{lambda(tbb::detail::d1::blocked_range<unsigned long>)#1}, tbb::detail::d1::auto_partitioner const>::execute(tbb::detail::d1::execution_data&) ()
#4  0x0000555556fa9f8b in tbb::detail::r1::market::process(rml::job&) ()
#5  0x0000555556f9a357 in tbb::detail::r1::rml::private_worker::thread_routine(void*) ()
#6  0x00007ffff6af239d in start_thread (arg=<optimized out>) at pthread_create.c:447
#7  0x00007ffff6b7749c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

Slicing other objects, or this object in a different orientation, works fine.

### Project file & How to reproduce

Here's the project I'm slicing (through File > Save project as):
[about to crash.zip](https://github.com/user-attachments/files/16986134/about.to.crash.zip)

Here's my config (through "export config bundle with physical printer"):
[SuperSlicer_config_bundle.zip](https://github.com/user-attachments/files/16986135/SuperSlicer_config_bundle.zip)

### Version

2.5.60.0

### Operating system

archlinux

### Printer model

voron 2.4 with 0.6 nozzle

**Comment by julian-weinert** [comment]
I'm facing the same issue on mac when slicing a simple box with vase mode enabled...
